# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_num', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
